# INSECURE. Provided as an example only.
on:
  push:
  pull_request_target:

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: write
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - run: |
        docker login ghcr.io -u token -p ${{ github.token }}
        docker pull alpine
        docker tag alpine ghcr.io/${{ github.repository }}
        docker push ghcr.io/${{ github.repository }}

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-node@v1

    - run: echo "Secret is ${{ secrets.MY_SECRET }}"

    - run: cat README.md
