# INSECURE. Provided as an example only.
on:
  push:
  pull_request_target:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - run: |
        docker login ghcr.io -u token -p ${{ github.token }}

    - name: pull ghcr.io
      run: |
        docker pull ghcr.io/${{ github.repository }}

    - name: push ghcr.io
      run: |
        docker pull alpine
        docker tag alpine ghcr.io/${{ github.repository }}
        docker push ghcr.io/${{ github.repository }}

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-node@v1

    - run: echo "Secret is ${{ secrets.MY_SECRET }}"

    - run: cat README.md
